    1  lsb_release -sc
    2  apt-get upduate && add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial universe"
    3  apt-get update && add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial universe"
    4  apt-cache search add-apt-repository
    5  apt-cache search aptitude
    6  apt-get install aptitude-common
    7  add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial universe"
    8  apt-get install software-properties-common
    9  add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial universe"
   10  history

